.gitignore
.travis.yml
assets/package-lock.json
mix.exs

ref: https://github.com/dwyl/app/issues/231

add .travis.yml configuration file

---

config/dev.exs
mix.exs
mix.lock

ref: #20
adding test, coveralls and credo on pre-commit

add pre-commit test command

---

.travis.yml

+ [x] Ensures that the coverage report is created and and sent to Codecov for issue #21

Run mix coveralls.json in .travis.yml #21

---

config/test.exs
lib/app/ctx/person.ex
lib/app_web/controllers/auth_controller.ex
lib/app_web/controllers/google_auth_controller.ex
lib/app_web/controllers/sessions_controller.ex
lib/app_web/router.ex
lib/app_web/templates/google_auth/index.html.eex
lib/elixir_auth_google/mock.ex
test/app_web/controllers/capture_controller_test.exs
test/app_web/controllers/categorise_controller_test.exs
test/app_web/controllers/google_auth_controller_test.exs
test/app_web/controllers/item_controller_test.exs
test/app_web/controllers/list_controller_test.exs
test/app_web/controllers/person_controller_test.exs
test/app_web/controllers/status_controller_test.exs
test/app_web/controllers/tag_controller_test.exs
test/app_web/controllers/timer_controller_test.exs
test/support/setup_helpers.ex

ref: https://github.com/dwyl/app/issues/252
Create an Auth controller/plug to manage sessions
Save session when user login
move restricted endpoint and use Auth plug to allow or deny access

add auth controller

---

lib/app/ctx.ex
lib/app/ctx/person.ex
mix.exs
priv/repo/seeds.exs
test/app/ctx_test.exs
test/app_web/controllers/status_controller_test.exs
test/support/setup_helpers.ex

ref: https://github.com/dwyl/app/issues/247#issuecomment-561708026
Create status data

add seed data for status

---

lib/app/ctx.ex
lib/app/ctx/person.ex
lib/app_web/controllers/auth_controller.ex
test/app/ctx_test.exs

Add suggestions from @nelsonic review on PR #24

Google auth review suggestions

---

.travis.yml
elixir_buildpack.config

udpdate erlang version for Heroku

---

.gitignore
README.md
lib/app_web/router.ex
mix.exs
mix.lock

ref: #56
Create new environment variable which let us define which urls/origins are allowed to access the API.

define which urls can send request to API

---

.env_sample
README.md
assets/package-lock.json
lib/app_web/router.ex
test/app_web/controllers/capture_controller_test.exs

+ [x] Update instructions for running the app on Localhost Fixes #58 
+ [x] Add `.env_sample` file with all necessary environment variables.
+ [x] Add link to Google App setup so people know how to create their API keys

Environment Variables Instructions issue #58

---

README.md

Add documentation for the creation of `sessions` table for https://github.com/dwyl/app/milestone/3
+ [x] Updated ER diagram
+ [x] Link to https://github.com/dwyl/elixir-auth-google

Update ER Diagram (Documentation) issue #60

---

README.md

resolve https://github.com/dwyl/app-mvp-phoenix/issues/83

fix hitcount

---

BUILDIT.md
lib/app/item.ex
lib/app_web/live/app_live.ex
lib/app_web/live/app_live.html.heex
test/app_web/live/app_live_test.exs

- Display footer with All, Active, Done and Archived links
- Filter items by status using LiveView
ref: #119

Filter items by status

---

BUILDIT.md
lib/app/item.ex
lib/app_web/live/app_live.ex
lib/app_web/live/app_live.html.heex
test/app_web/live/app_live_test.exs

Define filter status

---

lib/app_web/live/app_live.ex
lib/app_web/live/app_live.html.heex
lib/app_web/templates/layout/icons.html.heex
lib/app_web/templates/layout/live.html.heex
lib/app_web/templates/layout/root.html.heex

I've tried to follow the a11y guidelines outlined in #129

PR: Improve Accessibility #129

---

BUILDIT.md
lib/app_web/live/app_live.ex
test/app_web/live/app_live_test.exs

Avoid getting items from database when using filter
as this process is done on the view using the assings.items values
ref: #131

Remove Items query on filter

---

.github/workflows/ci.yml

PR: Remove Unused Environment Variables from `ci.yml` #133

---

BUILDIT.md
README.md
lib/app_web/templates/layout/root.html.heex

Fixes #142 ✅ 
Thanks @SimonLab

PR: update badges to "mvp" fixes #142 📝

---

lib/app_web/controllers/auth_controller.ex

use Phoenix.Component module to find assign_new function
related to: #153

Use Phoenix.Component module

---

lib/app_web/router.ex

Fix format error on `router.ex`
ref: https://github.com/dwyl/mvp/issues/183#issuecomment-1285160054

Run mix format

---

lib/app_web/templates/layout/root.html.heex

Make the login/logout button clickable
see: https://github.com/dwyl/mvp/issues/213#issuecomment-1324764804

Style links as buttons for login logout

---

.github/scripts/review-apps.sh
.github/workflows/review-apps.yml
build-review-apps.md
lib/app_web/live/app_live.html.heex

Start documentation on how to create a Github action for review apps

PR: Create Review Apps

---

BUILDIT.md
lib/app/item.ex
lib/app_web/live/stats_live.ex
test/app_web/live/stats_live_test.exs

closes #261 
Also updates the BUILDIT.MD with these changes.

[PR] Fixes stats page not loading and erronous incrementing

---

lib/app/item.ex
lib/app_web/live/app_live.ex
lib/app_web/live/app_live.html.heex

Save draft item when textarea value changes
see: #253

Create draft item

---

.github/workflows/fix-typos.yml
BUILDIT.md
lib/app_web/live/app_live.ex

Hello! 👋 
saw the [ticket](https://github.com/dwyl/technology-stack/issues/120) and added here 🔨 
typos that were found by the bot
Resolves https://github.com/dwyl/technology-stack/issues/120

GitHub Action to Prevent & Fix Typos

---

lib/app_web/templates/layout/root.html.heex

Micro-PR to:
+ [x] add plausible analytics see: #287 📈

PR: Add plausible analytics issue #287

---

lib/app_web/templates/layout/root.html.heex

+ [x] Add CSP for: https://github.com/dwyl/mvp/issues/287#issuecomment-1418919459

PR: add Content-Security-Policy to root.html 

---

lib/app_web/templates/layout/root.html.heex

+ [x] Debugging the `CSP` directive for #287

PR: inline both plausible and cloudflare in CSP #287

---

lib/app_web/templates/layout/root.html.heex

+ [x] Update as per: https://github.com/plausible/analytics/issues/2648 #287

PR: Simplify Content-Security-Policy #287

---

BUILDIT.md
lib/app_web/templates/layout/icons.html.heex
lib/app_web/templates/layout/root.html.heex

Place the content security policy in root to make it easier to find it.
Update BUILDIT with documentation

Place CSP in root.html

---

BUILDIT.md
api.md
build-review-apps.md
lib/app/item.ex
mix.exs
test/app/item_test.exs

chore(typos): fix typos

---

.github/dependabot.yml

Ref: https://github.com/dwyl/technology-stack/issues/126

PR: add ignore directive to `dependabot.yml` to avoid patch updates 

---

BUILDIT.md

closes #349 
Restores the sections with updated changes.

[PR] Restore Missing Metrics/Stats Docs

---

Dockerfile

closes #373 
I'm making changes to `fly.io` and the `Review App` only runs on PRs. This is a PR to check if these changes effectively solve the problem.

[PR] Checking if removing deprecated app helped

---

lib/app_web/live/app_live.ex
lib/app_web/live/app_live.html.heex
test/app_web/live/app_live_test.exs

[PR] Fixing timer text not updating when updating timer whilst it's running

---

.github/workflows/pr.yml
fly.toml

This PR updates the `fly.toml` file to `V2` #385

PR: Update Fly.io app from V1 to v2 #385
