lib/app/ctx.ex, lib/app/ctx/person.ex, lib/app_web/templates/person/form.html.eex, test/app/ctx_test.exs
=> update tests to use EmailHash field

lib/app/ctx/person.ex, lib/app_web/controllers/google_auth_controller.ex, lib/app_web/templates/google_auth/index.html.eex
ref: #29
Make sure users are not saved multiple times in the database by checking if the email_hash value already exists
=> Avoid person duplicate

lib/app_web/controllers/person_controller.ex, lib/app_web/router.ex, lib/app_web/templates/person/info.html.eex, test/app_web/controllers/page_controller_test.exs
ref: https://github.com/dwyl/app/issues/119
Allow people to logout from the application
=> add logout link on user info page

lib/app_web/controllers/captures_controller.ex, lib/app_web/controllers/item_controller.ex, lib/app_web/router.ex, lib/app_web/views/capture_view.ex, lib/app_web/views/item_view.ex, test/app_web/controllers/capture_controller_test.exs, test/app_web/controllers/item_controller_test.exs
ref: #53
Capture api endpoint.
To test you can run the sever as usual with `mix phx.sever` then run the following curl command:
```sh
curl --data "text=api capture test" localhost:4000/api/capture
```
The `text` field needs to be defined, otherwise the capture won't be saved and an error message is returned in a json format
=> Api capture list

lib/app/item.ex, lib/app/person.ex, lib/app/status.ex, lib/app_web/live/app_live.ex, lib/app_web/live/app_live.html.heex, priv/repo/migrations/20220627162141_create_status.exs, priv/repo/migrations/20220627162148_create_people.exs, priv/repo/migrations/20220627162154_create_items.exs, priv/repo/seeds.exs, test/app/item_test.exs, test/app/person_test.exs, test/app/timer_test.exs, test/app_web/live/app_live_test.exs
=> Ecto changeset associations

lib/app_web/live/app_live.html.heex
- Adjust height of textarea automatically
- use Tailwind to add a max-height
=> Use Alpine.js and Tailwind for Textarea size

lib/app_web/live/app_live.ex
- Use assigns[:person][:id] instead of if/else
- Run credo and fix some of the syntax issues reported
@nelsonic I let you decide if you want to add this to `main` or not
ref: #134
=> Update syntax for get_person_id function

.iex.exs, lib/app/item.ex, lib/app/person.ex, lib/app/tag.ex, lib/app_web/controllers/init_controller.ex, lib/app_web/controllers/profile_controller.ex, lib/app_web/controllers/tag_controller.ex, lib/app_web/router.ex, lib/app_web/templates/layout/root.html.heex, lib/app_web/templates/profile/edit.html.heex, lib/app_web/templates/profile/show.html.heex, lib/app_web/views/profile_view.ex, priv/repo/migrations/20221004195054_add_person.exs, test/app/item_test.exs, test/app/person_test.exs, test/app/tag_test.exs, test/app/timer_test.exs, test/app_web/controllers/profile_controller_test.exs, test/app_web/controllers/tag_controller_test.exs, test/app_web/live/app_live_test.exs
- Create people table with `person.id` and `name`
- Copy existing `person_id` from `items` and `tags`
- Add foreign key using references in `items` and `tags`
=> Create people migration

config/config.exs
Update the  `config.exs` file to use the latest Tailwind version (3.2)
You might need to run `mix tailwind.install` to download the latest version
ref: #188
=> Update Tailwind to use v3.2

BUILDIT.md, README.md
fixes #190 
As requested, here's the PR of the changes to README and possibly BUILD while running the MVP.
=> [PR] Updating README and BUILD.

priv/repo/migrations/20221114161649_update_text_type.exs, test/app/item_test.exs
Update type for item's text
ref: #204
=> PR: Create migration to change `item.text` type from `string` to `text`

lib/app_web/controllers/tag_controller.ex, lib/app_web/templates/tag/form.html.heex, lib/app_web/templates/tag/index.html.heex, lib/app_web/templates/tag/new.html.heex, test/app_web/controllers/tag_controller_test.exs
Display form for creating new tags
ref: https://github.com/dwyl/mvp/issues/201#issuecomment-1311648666
=> PR: Allow creating new `tag`

lib/app_web/templates/tag/index.html.heex
Add css classes to add ellipsis when tag name is too long to be displayed in the table
see: #217
=> Display long tag name with ellipsis

lib/app_web/templates/tag/index.html.heex
Use max width for tag name
see: https://github.com/dwyl/mvp/issues/217#issuecomment-1330710237
=> Use max-width instead of width for tag name

BUILDIT.md, lib/app_web/controllers/auth_controller.ex
This PR adds in application of `auth_plug`. Both the documentation within `BUILDIT` and `auth_controller` itself have been updated.
Question:
@nelsonic I saw you stated both instructions needed to be updated in the BUILDIT, but I didn't see where else this function was used. Were you referring to the second `on_mount` function at [auth_controller](https://github.com/dwyl/mvp/blob/78c06aea16d1436f08af3ac7da6578a70423ff38/lib/app_web/controllers/auth_controller.ex#L20)? If so, I didn't know if I needed to add the pattern matching for the `jwt` there as well. 
I think there's several blockers on this one. We've got two failing tests related to this change.
1. We're using `auth_plug` 1.4.14 in our `mix.exs` at [https://github.com/dwyl/mvp/blob/78c06aea16d1436f08af3ac7da6578a70423ff38/mix.exs#L …
=> PR: DRY Assign JWT to Socket Code issue #215

.github/workflows/review-apps.yml
Add condition to check author PR name and only run the Github action if the author is not dependabot
see: #259
=> Do not create review app for dependabot PRs

lib/api/localhost.json
closes #297
Stringifies the values inside the `localhost.json` file.
=> [PR] Fix failing API tests. 

lib/api/localhost.json, lib/app_web/live/app_live.html.heex
+ [x] Fixes the bug noted in #296 where the tag selector covers the selected tags.
=> PR: move selected `tags` above `tags` selector #296

lib/app_web/live/app_live.html.heex
Make sure the textarea is properly resized
when the text draft is saved
see: #305
=> Call resize() on x:init

lib/app_web/live/app_live.ex, lib/app_web/live/app_live.html.heex, test/app_web/live/app_live_test.exs
This PR adds the functionality to select Tags when the user presses Enter while searching for tags.
It will always pick the first tag that appears on the list, if there are no tags, nothing will be added.
The behavior is detailed on [the issue](https://github.com/dwyl/mvp/issues/308).
I tried to make it simple.
Please, let me know if you guys think it's needed any changes.
I didn't like the way I managed to empty the field after the user press Enter but I tried using LiveView <.input> with no success, if you guys have any other ideas let me know, I'd love to learn since I'm new to Phoenix/LiveView.
:D
=> Add Tag on task using Enter

lib/app/person.ex, lib/app_web/controllers/tag_controller.ex, lib/app_web/live/app_live.ex, lib/app_web/live/stats_live.ex, test/app/person_test.exs
This PR creates the Person Module and refactors to use the method created.
@nelsonic can you give some feedback if that's what you intended?
I searched on the code for other places that were using person-related stuff but the only thing that made sense to add on the module was this method.
Thank you!
=> Chore: Creates the Person module and refactors a little

BUILDIT.md, assets/js/app.js, lib/app_web/live/app_live.ex, lib/app_web/live/app_live.html.heex, test/app_web/live/app_live_test.exs
closes #416 
This renames events and variables in `assets/js/app.js`, `lib/app_web/live/app_live.ex` and `lib/app_web/live/app_live.html.heex`, as well as the respective tests.
`BUILDIT.md` has also been modified according to these changes.
=> chore: Making variables "snake_case" in drag and drop code

BUILDIT.md, lib/app/repo.ex, lib/app/stats.ex, lib/app/tag.ex, lib/app_web/controllers/tag_controller.ex, lib/app_web/live/stats_live.ex, lib/app_web/live/stats_live.html.heex, lib/app_web/live/tags_live.ex, lib/app_web/live/tags_live.html.heex, lib/app_web/router.ex, lib/app_web/templates/tag/index.html.heex, lib/app_web/views/tag_view.ex, test/app/repo_test.exs, test/app/stats_test.exs, test/app/tag_test.exs, test/app_web/controllers/tag_controller_test.exs, test/app_web/live/stats_live_test.exs, test/app_web/live/tags_live_test.exs
This improves the Tags Page to have much more details on its table #396.
I moved some common methods between Stats <-> Tag to do the sorting on the Repo module, maybe we could create a new module for it, but let's see what you guys think.
- Sorting the virtual columns https://github.com/dwyl/mvp/issues/436
=> Tags Page with more details

lib/app_web/live/app_live.html.heex
Quick fix for the timer starting from 00:00:00 on restart. There might be a nicer way to tidy this code up - I'm not well versed in AlpineJS though.
Let me know if you want to create an issue to track this - I just noticed when playing around and thought it would be easiest to submit a PR 😃
https://github.com/dwyl/mvp/assets/9089056/d7ed5ce1-9227-4be3-878f-f67f0469cf8a
=> fix: Timer starting from 00:00:00
